### PR TITLE
Feature: reworked examples and merging FCT jupyter notebooks to flasc

### PR DESCRIPTION
**Pull request by Bartdoekemeijer**
This PR is **ready** to be merged.

**Feature or improvement description**
This PR reworks the examples in accordance to #75.

**Related issue, if one exists**
#75.

**Impacted areas of the software**
Examples.

**Additional supporting information**
Everything should run out of the box and standalone.

**Test results, if applicable**
The Smarteole and Artificial examples should all work out of the box, without FCT dependencies.

### CODE REVIEW

**Comment by Bartdoekemeijer** [comment]
This PR **is ready to be merged**:
- Transferred over artificial example cases from FCT to FLASC and verified that they run on my system.
- Updated all smarteole example cases and verified that they run on my system.
- Updated /tests/ to make sure they all run on my system.
- Merged in latest develop changes.

See the notebooks with results in:
- https://github.com/Bartdoekemeijer/flasc/blob/feature/update_examples_notebooks/examples_artificial_data/raw_data_processing/filter_ws_power_curves.ipynb
- https://github.com/Bartdoekemeijer/flasc/blob/feature/update_examples_notebooks/examples_artificial_data/raw_data_processing/northing_calibration.ipynb
- https://github.com/Bartdoekemeijer/flasc/tree/feature/update_examples_notebooks/examples_smarteole

All examples now run successfully and in comparable fashion to FCT format. Also applied a couple bug fixes along the way to make sure all examples work with the recent changes to several plotting functions. @paulf81 @misi9170 @ejsimley could you review?

**Review by paulf81 — APPROVED** [review]
Thanks @Bartdoekemeijer  this is looking really great!  I have two comments but neither changes my decision to approve, maybe just for consideration:

1) I'm getting deprecation warnings about pandas append statements in the code, but I think better we handle this in the separate request, maybe after merging develop back into that one and finding all the appends

2) Maybe it's good if you recommit the notebooks with outputs cleared out?  There are some warnings relative to your machine that, while no big deal, maybe better they are cleared away for the user?  Downside will be the figures aren't there until running so here I'm also not positive?  Maybe we suppress certain warnings in the notebooks?

Otherwise, I downloaded an ran the examples and confirm they run great!

**Review by misi9170 — APPROVED** [review]

**Comment by Bartdoekemeijer** [comment]
Thanks for reviewing the code and the comments @paulf81 and @misi9170!

The deprecation warnings were because #86 was not yet merged into `develop`. So what I did was: 
1. Merge the latest changes in `main` (predominantly #86) into `develop`, see #96
2. Updated this repository with latest changes in `develop`
3. Re-ran the Jupyter Notebooks.

The code runs much faster now and the append warnings have been resolved. I also agree that Jupyter notebooks are tricky when it comes to Git and can easily clutter the Git history. The figures are super helpful to have, though, so I've opted to keep them in. I'll "Squash and Merge" so that we don't have a history of various Notebooks cluttering up our history.

**Comment by paulf81** [comment]
Sounds good to me @Bartdoekemeijer thank you!

**Pull request merged**
