### PR TITLE
Feature/type downsample

### PR DESCRIPTION
**Pull request by paulf81**
Is NOT ready to be merged

**Feature or improvement description**
Put in a very initial version of the downsample types function and a companion example, a number of caveats though
- not sure where the function should live
- not sure where the example should live
- function only handles floats for the moment

  Code based on stuff we've used previously and I tried to remove any mutations

**Related issue, if one exists**
Issue #38

### CODE REVIEW

**Comment by Bartdoekemeijer** [comment]
Hi Paul. Check this out: https://github.com/NREL/flasc/blob/8b6a21eee80f8eb20481ee4b3d4231d7c0c09699/flasc/dataframe_operations/dataframe_manipulations.py#L685

I forgot that I had written a function for this a while ago. It does a couple of additional things:
- Simplify 64-bit float columns to 32-bit float
- Simplify floats to integers if possible
- Simplify higher-bit integers to lower-bit integers (down to 8-bit) if possible
- Simplify from integer column to bool column if it contains only 0s and 1s

Additionally, I'd like to add functionality that recognizes strings, determines whether they can be better sorted as categories (like you previously suggested), and format them accordingly.

**Comment by Bartdoekemeijer** [comment]
> @Bartdoekemeijer huge miss on my part! Sorry for that! I've now removed the duplicate function and updated the new demo to point to your existing code and show it reduces mem usage by about 50%. Then I'll leave the pull open where we can add the other operations you mention above. Maybe also I need to move the location of this example, do you have a preferred folder?

Ha no worries, an even bigger oversight on my part since I wrote that function, haha! Yes, sounds good! Maybe we can just have the reduce operation in one of the raw_data_processing steps, early on. Maybe in `a_00_initial_download.py` or `a_01_to_common_format_df.py`?

**Comment by paulf81** [comment]
@Bartdoekemeijer  this could mean it will be in the new repository then right?  I mean like with Issue #48

**Comment by Bartdoekemeijer** [comment]
> @Bartdoekemeijer this could mean it will be in the new repository then right? I mean like with Issue #48
Yes, sounds good to me! I'm currently building such a template repository but haven't made it public yet. I'd like to get FLASC available through PyPI first. That will allow me to link the template repository to a specific version of FLASC. I'll open a separate issue for that.

**Comment by Bartdoekemeijer** [comment]
I think we can close this now that we have https://github.com/NREL/flasc_cookiecutter_template.

**Comment by paulf81** [comment]
Agreed I will close it now

**Pull request closed without merging**
