### PR TITLE
wind-up example

### PR DESCRIPTION
**Pull request by aclerc**
**Feature or improvement description**
Add a simple example of a wind-up uplift and uncertainty calculation
Add `flasc/utilities/wind_up_tools.py` as a place for helpful functions to use the wind-up package

**Related issue, if one exists**

**Impacted areas of the software**

**Additional supporting information**
I originally branched from main, hence the extra commits from christiannvaughn to README.
I also noticed a typo in the README so fixed it.
I also edited `flasc/data_processing/filtering.py` because I was getting an `AttributeError` from `lgd.legendHandles` when running the other smarteole example notebooks

**Test results, if applicable**
I'd be happy to add tests to `flasc/utilities/wind_up_tools.py` but have not done that yet as I thought a bit of discussion about the design would be good first

### CODE REVIEW

**Comment by aclerc** [comment]
This PR can be closed if #210 is preferred

**Comment by misi9170** [comment]
Thanks @aclerc ! I'll close this one in favor of #210

**Comment by aclerc** [comment]
> Thanks @aclerc ! I'll close this one in favor of #210

OK no problem @misi9170 . #210 has conflicts I guess due to being re-based, I assume you or someone in your team will fix those but if you're waiting on me let me know

**Comment by misi9170** [comment]
@aclerc , we will fix those---I had meant to get to it last week but there are a few complications coming from #211 that we're also working through. We're hoping to get those all dealt with soon.

**Pull request closed without merging**
