### PR TITLE
Feature: Addressing irregular turbine behavior of neighboring turbines (e.g., curtailment)

### PR DESCRIPTION
**Pull request by Bartdoekemeijer**
This PR **is not** ready to be merged. Requires review and creation of a unit test.

**Feature or improvement description**
We add a number of important features to address the issue described below. We add:
1. Add a function in `dataframe_operations.dataframe_filtering` that can mark a turbine's measurements as faulty if neighboring turbines that shed a wake on this turbine show outliers, e.g., when the neighboring turbine is curtailed or offline.
2. When calculating FLORIS predictions for a dataset, ensure that NaNs in the original dataset are copied over to the FLORIS predictions. This is done by adding a `mirror_nans` handle to `interpolate_floris_from_df_approx()`.

**Related issue, if one exists**
This PR fundamentally improves the way we do energy ratio comparisons. Specifically, we are currently not comparing apples to apples, partially because the issue raised in #27. Namely, if turbine A is curtailed and waking turbine B, we should accommodate for this in our analysis when looking at the energy ratios of turbine B. Currently, we just assume that turbine A is operating normally (non-curtailed) when we make the FLORIS predictions. The same problem occurs if a turbine is down -- FLORIS would still assume that turbine sheds a normal-operation-like wake on its neighboring turbines. This skews the analysis.

**Impacted areas of the software**

**Additional supporting information**
`floris_tools` and `dataframe_filtering`

**Test results, if applicable**
I'll open a pull request in the `flasc_cookiecutter_template` repository with example usage.

### CODE REVIEW

**Comment by Bartdoekemeijer** [comment]
Here's a demonstration of the feature:

```
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from flasc.dataframe_operations import dataframe_filtering as dff
from flasc import floris_tools as ftools
from flasc.visualization import plot_layout_only

from floris.tools import FlorisInterface


if __name__ == "__main__":
    # Read file and load FLORIS
    fi = FlorisInterface("/mnt/c/Users/Bart.Doekemeijer/OneDrive - Shell/Documents/python_scripts/flasc/examples/demo_dataset/demo_floris_input.yaml")
    plot_layout_only(fi)
    num_turbs = len(fi.layout_x)

    # Determine which turbines impact which other turbines through their wakes
    print("Calculating the 'df_impacting_turbines' matrix...")
    df_impacting_turbines = ftools.get_all_impacting_turbines(fi_in=fi, change_threshold=0.005)
    print(df_impacting_turbines)

    # Create tiny subset
    # dff.filter_df_by_faulty_waking_turbines
    df_base = pd.DataFrame({
        "wd": [255.0],
        "ws": [8.0],
        "ti": [0.07],
        "ws_000": [8.0],
        "ws_001": [8.0],
        "ws_002": [8.0],
        "ws_003": [8.0],
        "ws_004": [8.0],
        "ws_005": [8.0],
        "ws_006": [8.0],
        "pow_000": [2.3e6],
        "pow_001": [2.3e6],
        "pow_002": [2.3e6],
        "pow_003": [2.3e6],
        "pow_004": [2.3e6],
        "pow_005": [2.3e6],
        "pow_006": [2.3e6],
    })

    # Try a couple scenarios. 1st scenario: T04 waking T03 and T04 is NaN
    print("\n\n Creating scenario where T4 wakes T3 and T4 is faulty:")
    df = df_base.copy()
    df["wd"] = 275.0
    df["pow_004"] = np.nan
    for ti in range(num_turbs):
        df = dff.filter_df_by_faulty_waking_turbines(df=df, ti=ti, df_impacting_turbines=df_impacting_turbines)

    # Another scenario
    print("\n\n Creating scenario where T5 wakes T1 and T1 is faulty:")
    df = df_base.copy()
    df["wd"] = 357.0
    df["pow_001"] = np.nan
    for ti in range(num_turbs):
        df = dff.filter_df_by_faulty_waking_turbines(df=df, ti=ti, df_impacting_turbines=df_impacting_turbines)

    # Another scenario
    print("\n\n Creating scenario where T5 wakes T1 and T1 and T5 are faulty:")
    df = df_base.copy()
    df["wd"] = 357.0
    df["pow_001"] = np.nan
    df["pow_005"] = np.nan
    for ti in range(num_turbs):
        df = dff.filter_df_by_faulty_waking_turbines(df=df, ti=ti, df_impacting_turbines=df_impacting_turbines)

    # Another scenario
    print("\n\n Creating scenario where T5 wakes T1 and T5 is faulty:")
    df = df_base.copy()
    df["wd"] = 357.0
    df["pow_005"] = np.nan
    for ti in range(num_turbs):
        df = dff.filter_df_by_faulty_waking_turbines(df=df, ti=ti, df_impacting_turbines=df_impacting_turbines)

    # Another scenario
    print("\n\n Creating scenario where T5 wakes T1, T06 wakes T0, and T5 and T6 are faulty:")
    df = df_base.copy()
    df["wd"] = 357.0
    df["pow_005"] = np.nan
    df["pow_006"] = np.nan
    for ti in range(num_turbs):
        df = dff.filter_df_by_faulty_waking_turbines(df=df, ti=ti, df_impacting_turbines=df_impacting_turbines)

    plt.show()
```

and resulting in:
image

```
Calculating the 'df_impacting_turbines' matrix...
         0    1    2   3   4   5   6
wd                                  
0.0    [6]  [5]  [3]  []  []  []  []
2.0    [6]  [5]  [3]  []  []  []  []
4.0    [6]  [5]  [3]  []  []  []  []
6.0    [6]  [5]  [3]  []  []  []  []
8.0    [6]  [5]  [3]  []  []  []  []
...    ...  ...  ...  ..  ..  ..  ..
350.0  [6]  [5]  [3]  []  []  []  []
352.0  [6]  [5]  [3]  []  []  []  []
354.0  [6]  [5]  [3]  []  []  []  []
356.0  [6]  [5]  [3]  []  []  []  []
358.0  [6]  [5]  [3]  []  []  []  []

[180 rows x 7 columns]


 Creating scenario where T4 wakes T3 and T4 is faulty:
Faulty measurements for turbine 000 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 001 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 002 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 003 increased from 0.0 % to 100.0 %.
Faulty measurements for turbine 004 increased from 100.0 % to 100.0 %.
Faulty measurements for turbine 005 increased from 0.0 % to 100.0 %.
Faulty measurements for turbine 006 increased from 0.0 % to 100.0 %.


 Creating scenario where T5 wakes T1 and T1 is faulty:
Faulty measurements for turbine 000 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 001 increased from 100.0 % to 100.0 %.
Faulty measurements for turbine 002 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 003 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 004 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 005 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 006 increased from 0.0 % to 0.0 %.


 Creating scenario where T5 wakes T1 and T1 and T5 are faulty:
Faulty measurements for turbine 000 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 001 increased from 100.0 % to 100.0 %.
Faulty measurements for turbine 002 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 003 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 004 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 005 increased from 100.0 % to 100.0 %.
Faulty measurements for turbine 006 increased from 0.0 % to 0.0 %.


 Creating scenario where T5 wakes T1 and T5 is faulty:
Faulty measurements for turbine 000 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 001 increased from 0.0 % to 100.0 %.
Faulty measurements for turbine 002 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 003 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 004 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 005 increased from 100.0 % to 100.0 %.
Faulty measurements for turbine 006 increased from 0.0 % to 0.0 %.


 Creating scenario where T5 wakes T1, T06 wakes T0, and T5 and T6 are faulty:
Faulty measurements for turbine 000 increased from 0.0 % to 100.0 %.
Faulty measurements for turbine 001 increased from 0.0 % to 100.0 %.
Faulty measurements for turbine 002 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 003 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 004 increased from 0.0 % to 0.0 %.
Faulty measurements for turbine 005 increased from 100.0 % to 100.0 %.
Faulty measurements for turbine 006 increased from 100.0 % to 100.0 %.
```

Looks good to me!

**Comment by misi9170** [comment]
This looks really great @Bartdoekemeijer! One thing Paul and I discuss a little while ago is that the flagging of a given turbine as faulty due to its upstream turbine being faulty should not 'cascade', so to speak; in the first scenario above, T006 should not be marked as faulty _just because T003 is_ (it may be marked faulty though because it is still above the change threshold of T004). However, the use of df_impacting_turbines as you have it would only produce a 'cascade' if it was checked multiple times, which your code doesn't do, so I think that's the right approach!

For consistency in terminology, how do you feel about changing the name of the method from `filter_df_by_faulty_waking_turbines` to `filter_df_by_faulty_impacting_turbines`? The 'impacting' terminology is something that I didn't think about too much when coming up with it, but hopefully indicates the direction of the wake, if that makes sense.

I think it's best I let @paulf81 provide comments about the `mirror_nans` feature, but in principle it seems like a good idea to me.

**Comment by misi9170** [comment]
One other thought is that, if the intention is always to loop this over all turbines, it might actually be more straightforward to use the `get_all_dependent_turbines` function from floris_tools rather than the `get_all_impacting_turbines` function. That way, all you would have to do is:
1. Get the `df_dependent_turbines` dataframe using `get_all_dependent_turbines`
2. Check through the main df for faulty turbines. Any time a faulty turbine is found, check `df_dependent_turbines` at the given wind direction and mark all turbines found as faulty.

That procedure might be a little different in terms of ordering than the current filtering steps though, which look for reasons to remove data for a given test turbine sequentially. Also, there might be unnecessary overhead if you really just care about whether the data at one turbine is viable.

**Comment by Bartdoekemeijer** [comment]
Generally, the idea is to run this as part of the `raw_data_processing` folder. You do this once for all turbines post-northing-calibration. Indeed, you make a good point that we should avoid cascading these errors, so definitely good to be vigilant. By doing this only once and in `raw_data_processing`, the resulting dataset can be used without further consideration in all our energy ratio and visualization tools.

Also, good point @misi9170, I completely agree on the naming! I renamed the function to `filter_df_by_faulty_impacting_turbines` both here and in the FCT pull request.

On the reordering, I think you're right too @misi9170. Most often, we'll use this for all turbines, but I like the flexibility of being able to only run it on one or a handful of turbines. Also, the overhead is insignificant for now. In the example script, running
```
    for ti in range(num_turbs):
        df = dff.filter_df_by_faulty_waking_turbines(df=df, ti=ti, df_impacting_turbines=df_impacting_turbines)
```
Takes 20 milliseconds on my machine. I'm also OK having this function reorganized to work with `get_all_dependent_turbines`, but also fine leaving it as is.

**Comment by Bartdoekemeijer** [comment]
Also, putting in a reminder for myself before merging: I want to add the example script that I posted above as a unit test in `flasc/tests`.

**Comment by misi9170** [comment]
@Bartdoekemeijer, all sounds good to me. Given that this approach is slightly more flexible (can be used for checking just one or a few turbines) than it would be using `get_all_dependent_turbines`, I'm happy to leave it as is. We can investigate using `get_all_dependent_turbines` later if the need arises.

Thanks for the renaming! Sounds good also with the unit test. I'll go ahead and approve now.

**Review by paulf81 — APPROVED** [review]
Hi @Bartdoekemeijer, thank you for this, it looks very good.  I had only one thought and that was that for large farms it seems like getting "all" impacting turbines could be trouble for turbines at the rear of the farm, since they might require near perferct conditions for their data to be included.  In some work of yours, I did filtering by "most" impacting turbine.  Reviewing your code, I was thinking, this is fine in some sense, since the decision on which turbines are impacting is made outside the new functions right?  Anyway, just wanted to mention my reaction, but I think it might not have any ramifications to the code, just wondering how you use it (do you prefer all or "the most")?  Approving...

**Comment by Bartdoekemeijer** [comment]
> I had only one thought and that was that for large farms it seems like getting "all" impacting turbines could be trouble for turbines at the rear of the farm, since they might require near perferct conditions for their data to be included.

Good point! My guess would be that you just crank up `change_threshold=0.005` to `0.01`, for example. Really far upstream turbines don't really impact further downstream turbines I think.

Anyway, creating a unit test from the example and will tag you for a final approval and merge.

**Comment by misi9170** [comment]
> > I had only one thought and that was that for large farms it seems like getting "all" impacting turbines could be trouble for turbines at the rear of the farm, since they might require near perferct conditions for their data to be included.
> 
> Good point! My guess would be that you just crank up `change_threshold=0.005` to `0.01`, for example. Really far upstream turbines don't really impact further downstream turbines I think. I must also admit I haven't tried it out on large farms just yet. I'll definitely revisit this decision if it comes to that!
> 
> Anyway, creating a unit test from the example and will tag you for a final approval and merge.

@paulf81 @Bartdoekemeijer that's right. If too many turbines are being caught, one can either increase the `change_threshold` or set the `limit_number` argument to `get_all_impacting_turbines()`.

**Pull request merged**
