### PR TITLE
Feature: add interactive Bokeh plots in ws_pow_filtering

### PR DESCRIPTION
**Pull request by Bartdoekemeijer**
This PR is **ready** to be merged.

**Feature or improvement description**
This adds interactive browser-based Bokeh plot functionality to the windspeed-power curve filtering class. These figures can easily be saved as .htmls while maintaining their interactive functionality. You can zoom in/out, hide/show data with the legend, resize the plots, etc. This facilitates easy data exploring and additional in-depth analysis post-processing.

**Related issue, if one exists**
N/A

**Impacted areas of the software**
`ws_pow_filtering`

**Additional supporting information**
N/A

**Test results, if applicable**
I will share an example soon.

### CODE REVIEW

**Comment by Bartdoekemeijer** [comment]
I have updated `examples_artificial_data/filter_ws_pow_curves.ipynb` script to have the option to produce interactive figures with Bokeh, see [the Jupyter Notebook on the branch](https://github.com/Bartdoekemeijer/flasc/blob/feature/bokeh_plots/examples_artificial_data/raw_data_processing/filter_ws_power_curves.ipynb). I'm attaching two interactive figures in `.html` file format. GitHub won't allow me to upload the `.html` files directly, hence attaching them as `.zip` file: [figures.zip](https://github.com/NREL/flasc/files/11936433/figures.zip).  After unzipping, you can open them with your browser.

**Couple nice features with this Bokeh functionality:**
1. Figure is actively resized to your browser window size.
2. You can show/hide data points by clicking on them in the legend.
3. You can hover over data points to get information from them, e.g., the time and dataframe index to which the darapoint corresponds.
4. You can save these figures interactively, you for to investigate and modify them later. This is particularly helpful for inspecting data outside of the Jupyter notebook.

image

image

image

image

image

I'm not setting it as the default, but it's easy to enable for the interested user.

Last thing to do:
- [ ] Update docstring
- [ ] Review, maybe @paulf81 or @misi9170 can run the example case?

**Comment by Bartdoekemeijer** [comment]
OK pushed up docstring changes. Ready for review and then merge!

**Review by paulf81 — APPROVED** [review]
Hi @Bartdoekemeijer, thank you for this! I'm just doing my testing and wanted to just jot down two notes while on front of mind:

1) Should we add ipympl to the requirements? I think it is an additional requirement
2) Why the == specification for bokeh? Could we not use >=?

Other than that examples work great and I approve the improvement!

**Comment by Bartdoekemeijer** [comment]
Great, thank you @paulf81! I updated the `ipympl` and `bokeh` dependencies. Merging now.

**Pull request merged**
